  - name: Copy mysqlShellJsCommandsCommon for configuring the cluster
    become: yes
    template: src=mysqlJsCommandsCommon dest=/home/ubuntu/mysqlJsCommandsCommon  owner=root mode=0777
    when: "'172.31.43.58' in inventory_hostname"

  - name: Configure Cluster Common
    become: yes
    shell: mysqlsh  -f mysqlJsCommandsCommon
    when: "'172.31.43.58' in inventory_hostname"
