---
- hosts: "{{mysql_node_host_name1}} {{mysql_node_host_name2}} {{mysql_node_host_name3}}"
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - role: mysqlCommon
    - role: mysql11
    - role: mysql12
    - role: mysql13
    - role: mysql123
    - role: mysql21
    - role: mysql22
    - role: mysql23
    - role: mysqlLast
